# Generated by Django 4.2 on 2025-01-03 09:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XmlFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('object_type', models.CharField(db_comment='Miles Object Type', max_length=255)),
                ('object_ids', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(max_length=100), db_comment='Miles Object Ids', size=None)),
                ('timestamp', models.DateTimeField(db_comment='Date and time when the file was generated')),
            ],
        ),
    ]
