# Generated by Django 4.2 on 2025-01-03 09:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0002_xmlfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='status',
            field=models.CharField(choices=[('PREP', 'Preparation'), ('ONGOING', 'Ongoing'), ('DEPLOYED', 'Deployed')], default='PREP', max_length=24),
        ),
        migrations.AlterField(
            model_name='xmlfile',
            name='object_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), db_comment='Miles Object Ids', size=None),
        ),
    ]
